import React,{useState,useMemo} from 'react';
import {useShop} from '../context/ShopContext';
import {useLanguage} from '../context/LanguageContext';
import ProductCard from './ProductCard';
import LoadingGrid from './LoadingGrid';
export default function Catalog({search,setSearch,category,setCategory,sort,setSort}){
 const {catalog,loading}=useShop(),{t,category:translateCategory}=useLanguage(),[view,setView]=useState('grid');
 const products=useMemo(()=>{const q=search.toLowerCase();return (catalog?.products||[]).filter(p=>(category==='All'||(category==='Ground Chakras'?['Ground Chakras','Ground Chakkars'].includes(p.category):p.category===category))&&`${p.name} ${p.category}`.toLowerCase().includes(q)).sort((a,b)=>sort==='offers'?b.discount-a.discount:sort==='bestsellers'?b.sold-a.sold:Number(b.featured)-Number(a.featured));},[catalog,search,category,sort]);
 const categories=['All',...Array.from(new Set<string>((catalog?.products||[]).map(p=>p.category==='Ground Chakkars'?'Ground Chakras':p.category)))];
 return <section className="store-section catalog-section" id="catalog"><div className="section-heading"><div><h2>{t('Shop all crackers')}</h2><p className="muted" aria-live="polite">{products.length} {t('products')}{search?` ${t('for')} “${search}”`:''}</p></div><div className="catalog-actions"><div className="view-switch"><button aria-label={t('Grid view')} aria-pressed={view==='grid'} onClick={()=>setView('grid')}>▦</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}>☰ {t('Price list')}</button></div><select aria-label={t('Sort products')} value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">{t('Featured')}</option><option value="offers">{t('Best offers')}</option><option value="bestsellers">{t('Best sellers')}</option></select></div></div><div className="categories" aria-label={t('Product categories')}>{categories.map(c=><button key={c} className={c===category?'active':''} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c==='All'?t('All crackers'):translateCategory(c)}</button>)}</div>{loading?<LoadingGrid/>:<div className={'product-grid'+(view==='list'?' list':'')}>{products.map(p=><ProductCard key={p.id} product={p} label={p.sold?'Best seller':p.featured?'Shop favourite':''}/>)}{!products.length&&<div className="empty-state"><h3>{t('No matches found')}</h3><p>{t('Try another search or browse all crackers.')}</p><button className="button outline" onClick={()=>{setSearch('');setCategory('All');}}>{t('Clear filters')}</button></div>}</div>}</section>;
}
