import React,{useState,useRef} from 'react';
import {useShop} from '../context/ShopContext';
import {useLanguage} from '../context/LanguageContext';
import {request} from '../lib/api';
import LocationPicker from './LocationPicker';
import OrderSummary from './OrderSummary';
export default function Checkout({onBusy}){
 const {catalog,cart,setCart,totals,location,setLastOrder,online}=useShop(),{t}=useLanguage(),[name,setName]=useState(''),[mobile,setMobile]=useState(''),[alternateMobile,setAlternateMobile]=useState(''),[address,setAddress]=useState(''),[mode,setMode]=useState('delivery'),[saving,setSaving]=useState(false),[error,setError]=useState(''),lock=useRef(false),pending=useRef(null);
 async function submit(e){e.preventDefault();if(lock.current)return;if(mobile===alternateMobile){setError(t('Enter a different alternative contact number.'));return;}if(mode==='delivery'&&!location?.eligible){setError(t('Confirm a location inside our delivery area, or choose shop pickup.'));return;}const data={name,mobile,alternateMobile,address:mode==='delivery'?address:'',mode,lat:mode==='delivery'?location.lat:null,lng:mode==='delivery'?location.lng:null,items:cart.map(i=>({...i}))},signature=JSON.stringify(data);
  if(!pending.current){try{pending.current=JSON.parse(sessionStorage.getItem('kst-pending')||'null');}catch{}}
  if(pending.current?.signature!==signature){pending.current={signature,key:crypto.randomUUID()};try{sessionStorage.setItem('kst-pending',JSON.stringify(pending.current));}catch{}}
  lock.current=true;setSaving(true);onBusy(true);setError('');
  try{const order=await request('/api/orders',{data,timeout:15000,headers:{'Idempotency-Key':pending.current.key}});setLastOrder(order);setCart([]);try{sessionStorage.removeItem('kst-pending');}catch{}pending.current=null;}
  catch(err){setError(`${err.message} ${t('Your cart is safe; retry when ready.')}`);}
  finally{lock.current=false;setSaving(false);onBusy(false);}
 }
 const radius=catalog?.settings.radius??15,deliveryFee=mode==='delivery'?(catalog?.settings.deliveryFee||0):0;
 return <><OrderSummary subtotal={totals.subtotal} savings={totals.savings} deliveryFee={deliveryFee} quoteRequired={totals.quoteRequired}/><form onSubmit={submit}><fieldset className="checkout-fieldset" disabled={saving}><div className="form-grid"><label className="field">{t('Your name')}<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100} autoComplete="name"/></label><label className="field">{t('Mobile number')}<input type="tel" inputMode="numeric" value={mobile} onChange={e=>setMobile(e.target.value)} required pattern="[6-9][0-9]{9}" maxLength={10} autoComplete="tel-national" placeholder={t('10-digit mobile number')} title={t('Enter a 10-digit Indian mobile number')}/></label><label className="field">{t('Alternative contact number')}<input type="tel" inputMode="numeric" value={alternateMobile} onChange={e=>setAlternateMobile(e.target.value)} required pattern="[6-9][0-9]{9}" maxLength={10} autoComplete="off" placeholder={t('A different 10-digit number')} title={t('Enter a different 10-digit Indian mobile number')}/></label><label className="field">{t('Delivery option')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="delivery">{t('Door delivery')}</option><option value="pickup">{t('Shop pickup')}</option></select></label>{mode==='delivery'&&<div className="wide"><label className="field">{t('Full delivery address')}<textarea value={address} onChange={e=>setAddress(e.target.value)} required maxLength={1000} placeholder={t('House number, street, locality, PIN code, landmark')} autoComplete="street-address"/></label><LocationPicker/></div>}</div><p className="notice">{t('Delivery is limited to a {radius} km straight-line radius. Your contact numbers, address, and map location are saved for the shop admin only; contact numbers are not added to the WhatsApp quote. Stock is confirmed by the shop.',{radius})}</p><p className="error" role="alert">{error}</p>{!online&&<p className="error">{t('Reconnect to save your order. Your cart is safe.')}</p>}<button className="button primary checkout-submit" type="submit" disabled={!online||saving}>{saving?t('Saving your request…'):error?t('Retry saving request'):totals.quoteRequired?t('Request a quote from the shop'):t('Save request & get final quote')}</button></fieldset></form></>;
}
