import {useEffect,useRef,useState,FormEvent} from 'react';
import {request} from '../lib/api';
import {useLanguage} from '../context/LanguageContext';

type Promotion={id:string;enabled:boolean;title:string;titleTa?:string;drawAt:string;terms:string;termsTa?:string;gifts:{name:string;nameTa?:string;description:string;descriptionTa?:string}[];drawn:boolean};
type Slip={campaignId:string;code:string;created:string;drawAt:string};
export default function DiwaliGiftsWelcome({offer,onClose,preview=false}:{offer:Promotion;onClose:()=>void;preview?:boolean}){
 const {t,language}=useLanguage(),dialog=useRef<HTMLDialogElement>(null),[entryForm,setEntryForm]=useState(false),[restoreMode,setRestoreMode]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[slip,setSlip]=useState<Slip|null>(null);
 useEffect(()=>{const node=dialog.current;if(node&&!node.open)node.showModal();},[]);
 const close=()=>{try{sessionStorage.setItem(`kst-diwali-gifts-seen-${offer.id}`,'1');}catch{}dialog.current?.close();onClose();};
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const data=new FormData(event.currentTarget);try{const result=await request<{code:string;created:string;drawAt:string}>(restoreMode?'/api/diwali-prizes/wallet':'/api/diwali-prizes/entries',{data:{orderId:String(data.get('orderId')||''),name:String(data.get('name')||''),mobile:String(data.get('mobile')||''),address:String(data.get('address')||'')}});const receipt={campaignId:offer.id,code:result.code,created:result.created,drawAt:result.drawAt};try{const wallet=JSON.parse(localStorage.getItem('kst-diwali-wallet')||'[]');localStorage.setItem('kst-diwali-wallet',JSON.stringify([receipt,...(Array.isArray(wallet)?wallet.filter((item:Slip)=>item.campaignId!==offer.id):[])]));}catch{}setSlip(receipt);setEntryForm(false);setRestoreMode(false);}catch(e){setError(e instanceof Error?e.message:t('Please try again.'));}finally{setBusy(false);}}
 const drawDate=offer.drawAt?new Intl.DateTimeFormat(language==='ta'?'ta-IN':'en-IN',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(`${offer.drawAt}:00+05:30`)):'';
 return <dialog ref={dialog} className="lucky-welcome diwali-gifts-welcome" aria-labelledby="diwali-gifts-title" onCancel={event=>{event.preventDefault();close();}}>
  <div className="lucky-card"><button className="lucky-close" type="button" onClick={close} aria-label={t('Close Diwali prizes')}>×</button>
   <div className="lucky-art" aria-hidden="true"><span className="lucky-spark lucky-spark-one">✦</span><span className="lucky-spark lucky-spark-two">✧</span><div className="lucky-coupon"><small>KST · DIWALI SPECIAL</small><strong>SPECIAL<br/>PRIZES</strong><span>Five festive gifts</span></div><div className="lucky-gift">✦</div></div>
   <div className="lucky-copy"><span className="lucky-kicker">{t('Diwali celebration promotion')}</span><h2 id="diwali-gifts-title">{language==='ta'?(offer.titleTa||offer.title):offer.title}</h2><p>{t('{count} prizes for eligible customers; the same number of customers are selected at random from confirmed purchase entries.',{count:offer.gifts.length})}</p>
    <ol className="lucky-prizes">{offer.gifts.map((gift,index)=><li key={`${index}-${gift.name}`}><span className="prize-rank">{index+1}</span><span><strong>{language==='ta'&&gift.nameTa?gift.nameTa:gift.name}</strong>{(language==='ta'&&gift.descriptionTa?gift.descriptionTa:gift.description)&&<small>{language==='ta'&&gift.descriptionTa?gift.descriptionTa:gift.description}</small>}</span></li>)}</ol>
    <p className="lucky-date">{offer.drawn?t('The selection is complete. Contact the shop for details.'):drawDate?t('Selection starts at {date}; customers are selected between 09:00 and 10:00 India time.',{date:drawDate}):t('The shop will announce the selection date and time.')}</p>
    {preview?<><p className="lucky-terms" role="status">Local visual preview. Entry submission is disabled here.</p><button className="lucky-primary" type="button" onClick={close}>{t('Continue to the shop')}</button></>:!offer.enabled?<> <p className="lucky-terms" role="status">The prize promotion is not open yet. This preview shows {offer.gifts.length} configured prize{offer.gifts.length===1?'':'s'} ; entry opens after the shop announces the campaign date and terms.</p><button className="lucky-primary" type="button" onClick={close}>{t('Continue to the shop')}</button></>:slip?<div className="lucky-slip" role="status"><span>{t('Your entry receipt is saved in this device wallet.')}</span><strong>{slip.code}</strong></div>:entryForm?<form className="lucky-entry-form" onSubmit={submit}><p className="lucky-form-note">{t(restoreMode?'Recover the receipt using the same confirmed order reference, name and mobile number.':'Entry is available after the shop confirms your cracker order. Each order may be entered once. The same number of customers as configured prizes will be selected at random; entry does not guarantee a prize.')}</p><label>{t('Order reference')}<input name="orderId" required maxLength={100} autoComplete="off" placeholder="KST-…"/></label><label>{t('Your name')}<input name="name" required maxLength={100} autoComplete="name"/></label><label>{t('Mobile number')}<input name="mobile" type="tel" inputMode="numeric" pattern="[6-9][0-9]{9}" maxLength={10} required autoComplete="tel-national" placeholder={t('10-digit mobile number')}/></label>{!restoreMode&&<><label>{t('Gift delivery address')}<textarea name="address" rows={2} maxLength={1000} required autoComplete="street-address"/></label><label className="lucky-consent"><input type="checkbox" required/><span>{t('I agree that the shop can use these details to administer this promotion and contact me if selected.')}</span></label><p className="lucky-terms">{language==='ta'?(offer.termsTa||t(offer.terms)):offer.terms}</p></>}<p className="error" role="alert">{error}</p><button className="lucky-primary" disabled={busy||(!restoreMode&&offer.drawn)}>{busy?t('Saving…'):t(restoreMode?'Recover my receipt':'Submit my entry')}</button><button className="lucky-secondary" type="button" onClick={()=>{setEntryForm(false);setRestoreMode(false);setError('');}}>{t('Back to prizes')}</button></form>:<><p className="lucky-terms">{language==='ta'?(offer.termsTa||t(offer.terms)):offer.terms}</p><button className="lucky-primary" type="button" disabled={offer.drawn} onClick={()=>{setRestoreMode(false);setEntryForm(true);}}>{t('Enter with a confirmed order')} <span aria-hidden="true">→</span></button><button className="lucky-secondary" type="button" onClick={()=>{setRestoreMode(true);setEntryForm(true);}}>{t('Recover my entry receipt')}</button><button className="lucky-secondary" type="button" onClick={close}>{t('Continue to the shop')}</button></>}
    <small className="lucky-privacy">{t('Your entry receipt is stored on this device. Your contact details and address are visible only to shop administrators.')}</small>
   </div>
  </div>
 </dialog>;
}
