import {useShop} from '../context/ShopContext';
import {useLanguage} from '../context/LanguageContext';
import Icon,{type IconName} from './Icon';

interface HeaderProps{search:string;setSearch:(value:string)=>void;category:string;setCategory:(value:string)=>void;onSearch:()=>void;onOffers:()=>void}
const categoryIcons:Record<string,IconName>={'Sparklers':'sparkles','Flower Pots':'flower','Ground Chakkars':'wheel','Aerial':'rocket','Gift Boxes':'gift'};
export default function Header({search,setSearch,category,setCategory,onSearch,onOffers}:HeaderProps){
 const {catalog,totals,openCart,locate,locating,location,locationMessage}=useShop();
 const {language,t,toggleLanguage,category:translateCategory}=useLanguage();
 const categories:string[]=['All',...Array.from(new Set<string>((catalog?.products||[]).map(p=>p.category)))];
 const select=(value:string)=>{setCategory(value);onSearch();};
 const shortcuts=[{label:'Hot deals',caption:'More savings',icon:'tag' as IconName,tone:'orange',action:onOffers},{label:'Bundles',caption:'Better together',icon:'gift' as IconName,tone:'green',href:'#bundles'},{label:'Sparklers',caption:'Light up the evening',icon:'sparkles' as IconName,tone:'pink',action:()=>select('Sparklers')},{label:'Gift boxes',caption:'Celebration sets',icon:'gift' as IconName,tone:'blue',action:()=>select('Gift Boxes')},{label:'All crackers',caption:'Full collection',icon:'rocket' as IconName,tone:'gold',action:()=>select('All')}];
 return <header className="festival-header" id="home">
  <div className="brand-row"><a className="kst-brand" href="#home" aria-label={t('KST Crackers home')}><span className="brand-flower"><Icon name="sparkles"/></span><span>KST <b>crackers</b><small>{t('Celebration essentials')}</small></span></a><span className="festival-season"><span/>{t('YOUR CELEBRATION STORE')}</span><button className="language-toggle" onClick={toggleLanguage} aria-label={t(language==='en'?'Switch language to Tamil':'Switch language to English')} lang={language==='en'?'ta':'en'}>{language==='en'?'தமிழ்':'English'}</button><button className="desktop-cart" onClick={openCart}><Icon name="cart"/><span>{t('My cart')}</span><b>{totals.count}</b></button><button className="mobile-header-cart" onClick={openCart} aria-label={`${t('Open cart')}, ${totals.count}`}><Icon name="cart"/>{totals.count>0&&<b>{totals.count}</b>}</button></div>
  <div className="shortcut-row" aria-label={t('Quick shopping shortcuts')}>{shortcuts.map(s=>s.href?<a key={s.label} href={s.href} className={`shortcut-tile tile-${s.tone}`}><span className="shortcut-art"><Icon name={s.icon}/><i>✦</i></span><strong>{t(s.label)}</strong><small>{t(s.caption)}</small></a>:<button key={s.label} onClick={s.action} className={`shortcut-tile tile-${s.tone}`}><span className="shortcut-art"><Icon name={s.icon}/><i>✦</i></span><strong>{t(s.label)}</strong><small>{t(s.caption)}</small></button>)}</div>
  <div className="search-delivery-row"><form className="festival-search" role="search" onSubmit={e=>{e.preventDefault();onSearch();}}><Icon name="search"/><input id="shop-search" type="search" placeholder={t('Search crackers, bundles & more')} aria-label={t('Search crackers')} value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button type="button" className="clear-search" onClick={()=>setSearch('')} aria-label={t('Clear search')}>×</button>}<button className="search-go" aria-label={t('Search products')}><Icon name="arrow"/></button></form><button className="festival-location" onClick={locate} disabled={locating}><span className="location-pin"><Icon name="pin"/></span><span><strong>{locating?t('Finding your location…'):location?.eligible?t('We deliver to your location'):t('Check delivery to your address')}</strong><small>{location?.eligible?t('{distance} km from our hub',{distance:location.km.toFixed(1)}):t('Check delivery within {radius} km',{radius:catalog?.settings.radius??15})}</small></span><span className="location-action">{locating?t('Checking'):t('Locate me')}<Icon name="chevron"/></span></button></div>
  <p className={'header-delivery-status '+(location?.eligible?'success':'')} aria-live="polite">{locationMessage}</p>
  <nav className="festival-categories" aria-label={t('Browse cracker categories')}>{categories.map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>select(c)}><Icon name={categoryIcons[c]||'sparkles'}/><span>{c==='All'?t('For you'):translateCategory(c)}</span></button>)}</nav>
 </header>;
}
