import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {useShop} from '../context/ShopContext';
import {useLanguage} from '../context/LanguageContext';
import {money} from '../lib/helpers';
import Icon from './Icon';
import FestivalArtwork from './FestivalArtwork';
import CelebrationPacks from './CelebrationPacks';
const OrbitSparkles=dynamic(()=>import('./OrbitSparkles'),{ssr:false});
export type FestivalTheme='orange'|'green'|'pink'|'blue';
const themes:FestivalTheme[]=['orange','green','pink','blue'];
export default function Hero({onThemeChange}:{onThemeChange:(theme:FestivalTheme)=>void}){
 const {catalog}=useShop(),{t}=useLanguage(),track=useRef<HTMLDivElement>(null),[active,setActive]=useState(0),[playing,setPlaying]=useState(false);
 const maxDiscount=0,bundlePrice=catalog?.bundles.length?Math.min(...catalog.bundles.map(b=>b.price)):null,sparklerPrice=null;
 const slides=[{theme:'orange',eyebrow:'THE KST FESTIVAL EDIT',title:'Festival favourites.\nExceptional value.',detail:maxDiscount?`Up to ${maxDiscount}% off your festival favourites`:'Discover your festival favourites',badge:'Shop-confirmed pricing and availability',cta:'Explore the offers',href:'#offers'}, {theme:'green',eyebrow:'FAMILY TIME, BEAUTIFULLY BUNDLED',title:'One box.\nA complete celebration.',detail:bundlePrice?`Celebration bundles from ${money(bundlePrice)}`:'Handpicked celebration bundles',badge:'Handpicked combinations. One bundle price.',cta:'Find your bundle',href:'#bundles'}, {theme:'pink',eyebrow:'THE SPARKLER COLLECTION',title:'Light up\nthe little moments.',detail:sparklerPrice?`Sparklers starting at ${money(sparklerPrice)}`:'A little sparkle for your favourite people',badge:'Explore sizes and pack options',cta:'Shop the collection',href:'#category-sparklers'}, {theme:'blue',eyebrow:'YOUR FESTIVAL, YOUR WAY',title:'Your celebration.\nYour selection.',detail:'Get your quote, then confirm your order.',badge:`Local delivery within ${catalog?.settings.radius??15} km`,cta:'Start your celebration',href:'#catalog'}];
 function goTo(index:number){const el=track.current;if(!el)return;const child=el.children[index] as HTMLElement,padding=parseFloat(getComputedStyle(el).paddingLeft)||0;el.scrollTo({left:child.getBoundingClientRect().left-el.getBoundingClientRect().left+el.scrollLeft-padding,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});setActive(index);onThemeChange(themes[index]);}
 function syncSlide(){const el=track.current;if(!el)return;const children=Array.from(el.children) as HTMLElement[],padding=parseFloat(getComputedStyle(el).paddingLeft)||0;let index=0,nearest=Infinity;children.forEach((child,i)=>{const difference=Math.abs(child.getBoundingClientRect().left-el.getBoundingClientRect().left-padding);if(difference<nearest){nearest=difference;index=i;}});if(el.scrollLeft>=el.scrollWidth-el.clientWidth-2&&el.scrollLeft>0)index=themes.length-1;setActive(index);onThemeChange(themes[index]);}
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>goTo((active+1)%slides.length),5500);return()=>clearInterval(timer);},[playing,active]);
 const localizedSlides=slides.map(slide=>({...slide,eyebrow:t(slide.eyebrow),title:t(slide.title),detail:t(slide.detail),badge:t(slide.badge),cta:t(slide.cta)}));
 return <section className="festival-hero" aria-label={t('Festival offers')}>
  <div className="festival-intro"><div><span className="festival-eyebrow">{t('THE KST CELEBRATION EDIT')}</span><h1>{catalog?.settings.banner&&!['Big celebrations. Brilliant savings.','A little sparkle. A lot of celebration.'].includes(catalog.settings.banner)?catalog.settings.banner:t('Make your celebration brighter.')}</h1></div><span className="swipe-hint">{t('Explore the festival collection')} <Icon name="arrow"/></span></div>
  <div className="festival-track" ref={track} onScroll={syncSlide} onPointerDown={()=>setPlaying(false)}>{localizedSlides.map((slide,i)=><article className={`festival-slide slide-${slide.theme}`} key={slide.theme} aria-label={`${t('Offer')} ${i+1} / ${localizedSlides.length}`}><div className="slide-topline"><span>{slide.eyebrow}</span><Icon name="sparkles"/></div><h2>{slide.title.split('\n').map((line,j)=><span key={j}>{line}</span>)}</h2><p className="slide-detail">{slide.detail}</p><div className="slide-art">{i===0?<CelebrationPacks discount={maxDiscount}/>:i===1?<img className="bundle-hero-image" src="/images/family-celebration-bundle.webp" alt="" loading="eager" fetchPriority="high" decoding="async"/>:i===2?<div className="sparkler-artwork"><img className="sparkler-assortment-image" src="/images/sparkler-assortment.webp" alt="" loading="eager" decoding="async"/><OrbitSparkles/></div>:<img className="blue-fireworks-image" src="/images/diwali-gift-sky.webp" alt="" loading="eager" decoding="async"/>}<span className="art-caption">{t('KST · CELEBRATION ESSENTIALS')}</span></div><div className="slide-footer"><span className="slide-ribbon">{slide.badge}</span><a href={slide.href} className="slide-cta">{slide.cta}<Icon name="arrow"/></a></div><span className="slide-number">0{i+1} / 04</span></article>)}</div>
  <div className="carousel-controls"><span className="carousel-position" aria-live="polite">0{active+1} <span>/ 04</span></span><div className="carousel-dots" aria-label={t('Choose an offer')}>{localizedSlides.map((s,i)=><button key={s.theme} className={active===i?'active':''} onClick={()=>{setPlaying(false);goTo(i);}} aria-label={t('Show {offer}',{offer:s.eyebrow})} aria-pressed={active===i}/>)}</div><div className="carousel-arrows"><button onClick={()=>setPlaying(value=>!value)} aria-label={t(playing?'Pause offer slideshow':'Play offer slideshow')} aria-pressed={playing}><Icon name={playing?'pause':'play'}/></button><button onClick={()=>goTo(Math.max(0,active-1))} disabled={active===0} aria-label={t('Previous offer')}><Icon name="chevron" className="previous-arrow"/></button><button onClick={()=>goTo(Math.min(slides.length-1,active+1))} disabled={active===slides.length-1} aria-label={t('Next offer')}><Icon name="chevron"/></button></div></div>
 </section>;
}
