import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';

export type Language='en'|'ta';
const tamil:Record<string,string>={
 "Celebration essentials":"கொண்டாட்டத் தேவைகள்", "YOUR CELEBRATION STORE":"உங்கள் கொண்டாட்டக் கடை", "My cart":"என் கூடை",
 "Hot deals":"சிறப்பு சலுகைகள்", "More savings":"கூடுதல் சேமிப்பு", "Bundles":"தொகுப்புகள்", "Better together":"ஒன்றாகச் சிறப்பு", "Sparklers":"மத்தாப்புகள்", "Light up the evening":"மாலையை ஒளிரச் செய்யுங்கள்", "Gift boxes":"பரிசுப் பெட்டிகள்", "Celebration sets":"கொண்டாட்டத் தொகுப்புகள்", "All crackers":"அனைத்து பட்டாசுகள்", "Full collection":"முழுத் தொகுப்பு",
 "Search crackers, bundles & more":"பட்டாசுகள், தொகுப்புகளைத் தேடுங்கள்", "Search crackers":"பட்டாசுகளைத் தேடுங்கள்", "Clear search":"தேடலை அழிக்கவும்", "Search products":"பொருட்களைத் தேடுங்கள்", "Finding your location…":"உங்கள் இருப்பிடத்தைக் கண்டறிகிறது…", "We deliver to your location":"உங்கள் இடத்திற்கு விநியோகம் உண்டு", "Check delivery to your address":"உங்கள் முகவரிக்கு விநியோகம் உள்ளதா பார்க்கவும்", "{distance} km from our hub":"எங்கள் மையத்திலிருந்து {distance} கி.மீ.", "Check delivery within {radius} km":"{radius} கி.மீ.க்குள் விநியோகம் உள்ளதா பார்க்கவும்", "Checking":"சரிபார்க்கிறது", "Locate me":"என் இருப்பிடத்தைக் கண்டறி", "Browse cracker categories":"பட்டாசு வகைகளைப் பாருங்கள்", "For you":"உங்களுக்காக", "All":"அனைத்தும்", "Flower Pots":"பூந்தொட்டிகள்", "Ground Chakkars":"தரைச் சக்கரங்கள்", "Aerial":"வானவேடிக்கை",
 "Festival deals":"திருவிழாச் சலுகைகள்", "SAVE ON YOUR CELEBRATION":"கொண்டாட்டத்தில் சேமியுங்கள்", "See all offers":"அனைத்து சலுகைகளையும் பாருங்கள்", "New products coming soon.":"புதிய பொருட்கள் விரைவில் வரும்.", "Your most-loved crackers":"அதிகம் விரும்பப்பட்ட பட்டாசுகள்", "Featured crackers":"சிறப்புப் பட்டாசுகள்", "EXPLORE THE COLLECTION":"தொகுப்பைப் பாருங்கள்", "Browse favourites":"விருப்பமானவற்றைப் பாருங்கள்", "Best seller":"அதிகம் விற்பனையானது", "Shop favourite":"கடையின் விருப்பம்", "Festival offer":"திருவிழாச் சலுகை", "Shop all crackers":"அனைத்து பட்டாசுகளையும் பாருங்கள்",
 "CURATED CELEBRATION SETS":"தேர்ந்தெடுத்த கொண்டாட்டத் தொகுப்புகள்", "Celebration bundles":"கொண்டாட்டத் தொகுப்புகள்", "Loading bundle offers…":"தொகுப்புச் சலுகைகள் ஏற்றப்படுகின்றன…", "packs":"பெட்டிகள்", "varieties":"வகைகள்", "Save {amount}":"{amount} சேமிக்கவும்", "What’s in the box":"பெட்டியில் என்னென்ன?", "Product":"பொருள்", "Bundle price":"தொகுப்பின் விலை", "Add bundle":"தொகுப்பைச் சேர்க்கவும்", "Sold out":"கையிருப்பு இல்லை", "New bundles coming soon.":"புதிய தொகுப்புகள் விரைவில் வரும்.",
 "Shop all":"அனைத்தையும் பாருங்கள்", "Home":"முகப்பு", "Offers":"சலுகைகள்", "Cart":"கூடை", "THE KST FESTIVAL EDIT":"KST திருவிழா சிறப்புத் தேர்வு", "Festival favourites.\nExceptional value.":"திருவிழா விருப்பங்கள்.\nசிறந்த விலை.", "Up to {discount}% off your festival favourites":"விருப்பமான பட்டாசுகளுக்கு {discount}% வரை தள்ளுபடி", "Discover your festival favourites":"உங்கள் திருவிழா விருப்பங்களைத் தேர்ந்தெடுங்கள்", "Discounts shown in your final quote":"இறுதி விலைப்பட்டியலில் தள்ளுபடி தெரியும்", "Explore the offers":"சலுகைகளைப் பாருங்கள்", "FAMILY TIME, BEAUTIFULLY BUNDLED":"குடும்ப நேரத்திற்கான அழகான தொகுப்பு", "One box.\nA complete celebration.":"ஒரு பெட்டி.\nமுழுமையான கொண்டாட்டம்.", "Celebration bundles from {price}":"கொண்டாட்டத் தொகுப்புகள் {price} முதல்", "Handpicked celebration bundles":"தேர்ந்தெடுத்த கொண்டாட்டத் தொகுப்புகள்", "Handpicked combinations. One bundle price.":"தேர்ந்தெடுத்த பொருட்கள். ஒரே தொகுப்பு விலை.", "Find your bundle":"உங்கள் தொகுப்பைத் தேர்ந்தெடுங்கள்", "THE SPARKLER COLLECTION":"மத்தாப்புத் தொகுப்பு", "Light up\nthe little moments.":"சிறு தருணங்களை\nஒளிரச் செய்யுங்கள்.", "Sparklers starting at {price}":"மத்தாப்புகள் {price} முதல்", "A little sparkle for your favourite people":"உங்கள் அன்பானவர்களுக்கு சிறு ஒளிச்சுடர்", "Explore sizes and pack options":"அளவு மற்றும் பெட்டி விவரங்களைப் பாருங்கள்", "Shop the collection":"தொகுப்பை வாங்குங்கள்", "YOUR FESTIVAL, YOUR WAY":"உங்கள் திருவிழா, உங்கள் விருப்பம்", "Your celebration.\nYour selection.":"உங்கள் கொண்டாட்டம்.\nஉங்கள் தேர்வு.", "Build a quote. Send it on WhatsApp.":"விலைப்பட்டியல் தயார் செய்து WhatsApp-ல் அனுப்புங்கள்.", "Local delivery within {radius} km":"{radius} கி.மீ.க்குள் உள்ளூர் விநியோகம்", "Start your celebration":"கொண்டாட்டத்தைத் தொடங்குங்கள்", "THE KST CELEBRATION EDIT":"KST கொண்டாட்டச் சிறப்புத் தேர்வு", "Make your celebration brighter.":"உங்கள் கொண்டாட்டத்தை இன்னும் ஒளிரச் செய்யுங்கள்.", "Explore the festival collection":"திருவிழாத் தொகுப்பைப் பாருங்கள்", "Choose an offer":"சலுகையைத் தேர்ந்தெடுங்கள்", "Show {offer}":"{offer} சலுகையைக் காட்டுங்கள்", "Pause offer slideshow":"சலுகைத் திரையிடலை நிறுத்து", "Play offer slideshow":"சலுகைத் திரையிடலை இயக்கு", "Previous offer":"முந்தைய சலுகை", "Next offer":"அடுத்த சலுகை",
 "Local delivery":"உள்ளூர் விநியோகம்", "Within {radius} km of our shop":"எங்கள் கடையிலிருந்து {radius} கி.மீ.க்குள்", "Clear pricing":"தெளிவான விலை", "See discounts in your itemised quote":"விலைப்பட்டியலில் தள்ளுபடியைப் பாருங்கள்", "Shop-confirmed orders":"கடை உறுதிப்படுத்தும் ஆர்டர்கள்", "Confirm stock and delivery on WhatsApp":"கையிருப்பு, விநியோகத்தை WhatsApp-ல் உறுதிசெய்யுங்கள்", "Shopping with KST":"KST-யுடன் ஷாப்பிங்", "products":"பொருட்கள்", "Grid view":"கட்டக் காட்சி", "Price list":"விலைப் பட்டியல்", "Featured":"சிறப்பு", "Best offers":"சிறந்த சலுகைகள்", "Best sellers":"அதிகம் விற்பனையானவை", "Price: low to high":"விலை: குறைவிலிருந்து அதிகம்", "Price: high to low":"விலை: அதிகத்திலிருந்து குறைவு", "No matches found":"பொருத்தமானவை இல்லை", "Try another search or browse all crackers.":"வேறு சொல்லைத் தேடுங்கள் அல்லது எல்லா பட்டாசுகளையும் பாருங்கள்.", "Clear filters":"வடிகட்டிகளை அழி", "Available for order":"ஆர்டர் செய்யலாம்", "Currently unavailable":"தற்போது கிடைக்கவில்லை", "Add another":"மேலும் சேர்க்கவும்", "Add to cart":"கூடையில் சேர்", "{count} in cart":"கூடையில் {count}", "{name} added to your cart":"{name} கூடையில் சேர்க்கப்பட்டது", "You have reached the available quantity.":"கிடைக்கும் அளவை எட்டிவிட்டீர்கள்.", "No more stock available.":"கூடுதல் கையிருப்பு இல்லை.",
 "YOUR CELEBRATION CART":"உங்கள் கொண்டாட்டக் கூடை", "Shopping cart":"ஷாப்பிங் கூடை", "Close cart":"கூடையை மூடு", "Your cart is empty":"உங்கள் கூடை காலியாக உள்ளது", "Explore the latest offers and add your celebration favourites.":"சலுகைகளைப் பார்த்து விருப்பமானவற்றைக் கூடையில் சேருங்கள்.", "Start shopping":"ஷாப்பிங்கைத் தொடங்குங்கள்", "each":"ஒவ்வொன்றும்", "Remove one {name}":"{name} ஒன்றை நீக்கு", "Add one {name}":"{name} ஒன்றைச் சேர்", "You save":"நீங்கள் சேமிப்பது", "Products":"பொருட்கள்", "Delivery":"விநியோகம்", "Quote total":"மொத்த விலை",
 "Your name":"உங்கள் பெயர்", "Mobile number":"கைபேசி எண்", "Alternative contact number":"மாற்றுத் தொடர்பு எண்", "10-digit mobile number":"10 இலக்க கைபேசி எண்", "A different 10-digit number":"வேறொரு 10 இலக்க எண்", "Enter a 10-digit Indian mobile number":"இந்தியாவின் 10 இலக்க கைபேசி எண்ணை உள்ளிடுங்கள்", "Enter a different 10-digit Indian mobile number":"வேறொரு இந்திய 10 இலக்க கைபேசி எண்ணை உள்ளிடுங்கள்", "Delivery option":"விநியோக முறை", "Door delivery":"வீட்டிற்கு விநியோகம்", "Shop pickup":"கடையில் பெற்றுக்கொள்ளுதல்", "Full delivery address":"முழு விநியோக முகவரி", "House number, street, locality, PIN code, landmark":"வீட்டு எண், தெரு, பகுதி, அஞ்சல் குறியீடு, அடையாளம்", "Delivery is limited to a {radius} km straight-line radius. Your contact numbers, address, and map location are saved for the shop admin only; contact numbers are not added to the WhatsApp quote. Stock is confirmed by the shop.":"{radius} கி.மீ. சுற்றளவுக்குள் மட்டுமே விநியோகம். தொடர்பு எண்கள், முகவரி, வரைபட இடம் கடை நிர்வாகிக்காக மட்டும் சேமிக்கப்படும். WhatsApp விலைச் செய்தியில் எண்கள் சேர்க்கப்படாது. கையிருப்பை கடை உறுதிசெய்யும்.", "Saving your request…":"கோரிக்கை சேமிக்கப்படுகிறது…", "Retry saving request":"மீண்டும் சேமிக்கவும்", "Save request & get final quote":"கோரிக்கையைச் சேமித்து இறுதி விலையைப் பெறுங்கள்", "Enter a different alternative contact number.":"வேறொரு மாற்றுத் தொடர்பு எண்ணை உள்ளிடுங்கள்.", "Confirm a location inside our delivery area, or choose shop pickup.":"விநியோகப் பகுதிக்குள் உள்ள இடத்தை உறுதிசெய்யுங்கள் அல்லது கடையில் பெற்றுக்கொள்ளுங்கள்.", "Your cart is safe; retry when ready.":"உங்கள் கூடை பாதுகாப்பாக உள்ளது; தயாரானதும் மீண்டும் முயற்சிக்கவும்.",
 "Your order request is saved":"உங்கள் ஆர்டர் கோரிக்கை சேமிக்கப்பட்டது", "Reference":"குறிப்பு எண்", "Savings":"சேமிப்பு", "Final quote":"இறுதி விலை", "Send request on WhatsApp":"WhatsApp-ல் கோரிக்கையை அனுப்புங்கள்", "The shop has not configured its WhatsApp number yet.":"கடையின் WhatsApp எண் இன்னும் அமைக்கப்படவில்லை.", "Call shop":"கடைக்குத் தொலைபேசி செய்யுங்கள்", "Tap Send in WhatsApp. Your address and map location stay in the admin orders section and are excluded from the message. The shop will confirm stock and delivery.":"WhatsApp-ல் அனுப்பு என்பதைத் தட்டுங்கள். முகவரி, வரைபட இடம் நிர்வாக ஆர்டர்களில் மட்டும் இருக்கும்; செய்தியில் சேராது. கையிருப்பு, விநியோகத்தை கடை உறுதிசெய்யும்.", "Continue shopping":"தொடர்ந்து வாங்குங்கள்",
 "Check delivery to your location":"உங்கள் இடத்திற்கு விநியோகம் உள்ளதா பார்க்கவும்", "Enable location":"இருப்பிடத்தை இயக்கு", "Update location":"இருப்பிடத்தைப் புதுப்பி", "Checking location…":"இருப்பிடம் சரிபார்க்கப்படுகிறது…", "Use my location":"என் இருப்பிடத்தைப் பயன்படுத்து", "View selected delivery pin on map ↗":"தேர்ந்த விநியோக இடத்தை வரைபடத்தில் காண்க ↗", "Choose a different delivery pin":"வேறு விநியோக இடத்தைத் தேர்ந்தெடுக்கவும்", "Select the delivery pin in your map app and copy its coordinates here.":"வரைபடத்தில் விநியோக இடத்தைத் தேர்ந்தெடுத்து அதன் ஆயத்தொலைவுகளை இங்கே உள்ளிடுங்கள்.", "Latitude":"அட்சரேகை", "Longitude":"தீர்க்கரேகை", "Enter both map coordinates.":"இரண்டு வரைபட ஆயத்தொலைவுகளையும் உள்ளிடுங்கள்.", "Confirm delivery pin":"விநியோக இடத்தை உறுதிசெய்",
 "Back to top ↑":"மேலே செல்லுங்கள் ↑", "Every celebration starts with a little sparkle.":"ஒவ்வொரு கொண்டாட்டமும் சிறு ஒளிச்சுடரில் தொடங்குகிறது.", "Sample catalogue. Product artwork is illustrative. All requests require shop confirmation.":"மாதிரி பட்டியல். படங்கள் விளக்கத்திற்கானவை. எல்லா கோரிக்கைகளையும் கடை உறுதிசெய்யும்.", "How to place your order":"ஆர்டர் செய்வது எப்படி", "Fill your cart":"கூடையை நிரப்புங்கள்", "Choose crackers and bundles. See your savings instantly.":"பட்டாசுகள், தொகுப்புகளைத் தேர்ந்தெடுத்து சேமிப்பைப் பாருங்கள்.", "Get your quote":"விலைப்பட்டியலைப் பெறுங்கள்", "Choose delivery or pickup. Save your request with the shop.":"விநியோகம் அல்லது கடையில் பெறுதல் தேர்வு செய்து கோரிக்கையைச் சேமியுங்கள்.", "Send on WhatsApp":"WhatsApp-ல் அனுப்புங்கள்", "Tap Send with your quote. The shop confirms availability.":"விலைப்பட்டியலுடன் அனுப்பு என்பதைத் தட்டுங்கள். கிடைப்பதை கடை உறுதிசெய்யும்.",
 "Big moments deserve a beautiful box.":"பெரிய தருணங்களுக்கு அழகான பரிசுப் பெட்டி.", "Planning for a wedding, a team or a whole community? Explore gift boxes for bulk celebrations across the Nilgiris.":"திருமணம், குழு அல்லது சமூகக் கொண்டாட்டமா? நீலகிரி முழுவதற்குமான மொத்தப் பரிசுப் பெட்டிகளைப் பாருங்கள்.", "Gift boxes in bulk":"மொத்தப் பரிசுப் பெட்டிகள்", "Nilgiris-wide enquiries":"நீலகிரி முழுவதற்குமான விசாரணைகள்", "Personal quote":"தனிப்பட்ட விலைப்பட்டியல்", "Explore gift boxes":"பரிசுப் பெட்டிகளைப் பாருங்கள்", "Continue to the shop":"கடைக்குச் செல்லுங்கள்", "Bulk delivery, stock and final price are confirmed by the shop.":"மொத்த விநியோகம், கையிருப்பு, இறுதி விலையை கடை உறுதிசெய்யும்.", "Close bulk gift box offer":"மொத்தப் பரிசுப் பெட்டி சலுகையை மூடு", "KST CELEBRATION SPECIAL":"KST கொண்டாட்டச் சிறப்பு", "Made for moments together":"ஒன்றாகக் கொண்டாடும் தருணங்களுக்காக",
 "You’re offline. Your cart is safe. Reconnect to load products or save an order.":"இணைய இணைப்பு இல்லை. கூடை பாதுகாப்பாக உள்ளது. பொருட்களை ஏற்ற அல்லது ஆர்டர் செய்ய மீண்டும் இணையுங்கள்.", "Finding your festival favourites…":"திருவிழா விருப்பங்கள் ஏற்றப்படுகின்றன…", "Retry loading":"மீண்டும் ஏற்று", "The catalogue is loading. Please try shortly.":"பொருள் பட்டியல் ஏற்றப்படுகிறது. சிறிது நேரத்தில் முயற்சிக்கவும்.", "Turn on location to check delivery within {radius} km of our hub.":"மையத்திலிருந்து {radius} கி.மீ.க்குள் விநியோகம் உள்ளதா பார்க்க இருப்பிடத்தை இயக்குங்கள்.", "Delivery hub is not configured yet. Shop pickup is available.":"விநியோக மையம் இன்னும் அமைக்கப்படவில்லை. கடையில் பெற்றுக்கொள்ளலாம்.", "Delivery available · {distance} km from our hub":"விநியோகம் உண்டு · மையத்திலிருந்து {distance} கி.மீ.", "Outside our {radius} km delivery area · Shop pickup available":"{radius} கி.மீ. விநியோகப் பகுதிக்கு வெளியே · கடையில் பெற்றுக்கொள்ளலாம்.", "Location permission denied. Allow access in browser settings, or enter your delivery pin at checkout.":"இருப்பிட அனுமதி மறுக்கப்பட்டது. உலாவி அமைப்பில் அனுமதியளிக்கவும் அல்லது checkout-ல் இடத்தை உள்ளிடவும்.", "Location unavailable. Turn on device location, or enter your delivery pin at checkout.":"இருப்பிடம் கிடைக்கவில்லை. சாதன இருப்பிடத்தை இயக்கவும் அல்லது checkout-ல் இடத்தை உள்ளிடவும்.", "Location unavailable. Enter a delivery pin at checkout.":"இருப்பிடம் கிடைக்கவில்லை. checkout-ல் விநியோக இடத்தை உள்ளிடுங்கள்.", "Unable to reach the shop. Check your connection and retry.":"கடையுடன் இணைக்க முடியவில்லை. இணையத்தைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", "The shop is still loading. Please retry shortly.":"கடை ஏற்றப்படுகிறது. சிறிது நேரத்தில் முயற்சிக்கவும்.", "English":"ஆங்கிலம்", "தமிழ்":"தமிழ்", "Switch language to Tamil":"தமிழுக்கு மாற்று", "Switch language to English":"ஆங்கிலத்திற்கு மாற்று", "KST Crackers home":"KST பட்டாசுகள் முகப்பு", "Open cart":"கூடையைத் திற"
 ,"OFF":"தள்ளுபடி", "items":"பொருட்கள்", "View cart":"கூடையைப் பாருங்கள்", "Mobile shop navigation":"கைபேசி கடை வழிசெலுத்தல்", "Sort products":"பொருட்களை வரிசைப்படுத்து", "Product categories":"பொருள் வகைகள்", "Reconnect to save your order. Your cart is safe.":"ஆர்டரைச் சேமிக்க இணையத்தை மீண்டும் இணைக்கவும். உங்கள் கூடை பாதுகாப்பாக உள்ளது.", "Quick shopping shortcuts":"விரைவு ஷாப்பிங்", "Offer":"சலுகை", "Save up to {discount}% on selected crackers":"தேர்ந்தெடுத்த பட்டாசுகளுக்கு {discount}% வரை சேமியுங்கள்", "KST celebration packs":"KST கொண்டாட்டப் பெட்டிகள்", "SAVE UP TO":"வரை சேமிப்பு", "on selected crackers":"தேர்ந்தெடுத்த பட்டாசுகளுக்கு", "The shop could not display this page. Your saved cart is safe.":"கடையைத் திறக்க முடியவில்லை. உங்கள் சேமித்த கூடை பாதுகாப்பாக உள்ளது.", "Reload shop":"கடையை மீண்டும் ஏற்று", "for":"க்கான"
};

interface LanguageContextValue{language:Language;setLanguage:(language:Language)=>void;toggleLanguage:()=>void;t:(key:string,values?:Record<string,string|number>)=>string;category:(key:string)=>string}
const LanguageContext=createContext<LanguageContextValue|null>(null);
export function LanguageProvider({children}:{children:React.ReactNode}){
 const [language,setLanguageState]=useState<Language>('en');
 useEffect(()=>{try{const saved=localStorage.getItem('kst-language');if(saved==='ta'||saved==='en')setLanguageState(saved);}catch{}},[]);
 const setLanguage=(next:Language)=>{setLanguageState(next);try{localStorage.setItem('kst-language',next);}catch{}};
 const value=useMemo<LanguageContextValue>(()=>({language,setLanguage,toggleLanguage:()=>setLanguage(language==='en'?'ta':'en'),t:(key,values={})=>{let result=language==='ta'?(tamil[key]||key):key;for(const [name,value] of Object.entries(values))result=result.replaceAll(`{${name}}`,String(value));return result;},category:(key)=>language==='ta'?(tamil[key]||key):key}),[language]);
 return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error('LanguageProvider is missing');return value;}
