import React,{createContext,useContext,useState,useEffect,useCallback,useRef,useMemo} from 'react';
import {request} from '../lib/api';
import {readCart,sellingPrice,distance} from '../lib/helpers';
import {useLanguage} from './LanguageContext';
export const ShopContext=createContext<any>(null);
export const useShop=()=>useContext(ShopContext);
export function ShopProvider({children}){
 const {t}=useLanguage();
 const [catalog,setCatalog]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[cart,setCart]=useState([]),[cartReady,setCartReady]=useState(false),[toast,setToast]=useState(''),[location,setLocation]=useState(null),[locating,setLocating]=useState(false),[locationError,setLocationError]=useState(''),[cartOpen,setCartOpen]=useState(false),[lastOrder,setLastOrder]=useState(null),[online,setOnline]=useState(true);
 const loadController=useRef(null),toastTimer=useRef(null),locationLock=useRef(false);
 const notify=useCallback(message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3500);},[]);
 const loadCatalog=useCallback(async()=>{loadController.current?.abort();const controller=new AbortController();loadController.current=controller;setLoading(true);setError('');try{const data=await request('/api/catalog',{signal:controller.signal});if(!Array.isArray(data.products)||!Array.isArray(data.bundles)||!data.settings)throw new Error('Invalid catalogue response. Please retry.');if(controller.signal.aborted)return;setCatalog(data);setCart(previous=>previous.filter(i=>data.products.some(p=>p.id===i.id)||data.bundles.some(p=>p.id===i.id)));}catch(e){if(!controller.signal.aborted)setError(e.message);}finally{if(!controller.signal.aborted)setLoading(false);}},[]);
 useEffect(()=>{loadCatalog();return()=>{loadController.current?.abort();clearTimeout(toastTimer.current);};},[loadCatalog]);
 useEffect(()=>{setCart(readCart());setCartReady(true);setOnline(navigator.onLine);},[]);
 useEffect(()=>{if(!cartReady)return;try{localStorage.setItem('kst-cart',JSON.stringify(cart));}catch{}},[cart,cartReady]);
 useEffect(()=>{const connected=()=>setOnline(navigator.onLine);window.addEventListener('online',connected);window.addEventListener('offline',connected);return()=>{window.removeEventListener('online',connected);window.removeEventListener('offline',connected);};},[]);
 useEffect(()=>{if(online&&!catalog&&!loading)loadCatalog();},[online]);
 const findProduct=useCallback(id=>catalog?.products.find(p=>p.id===id)||catalog?.bundles.find(p=>p.id===id),[catalog]);
 function addToCart(id){const p=findProduct(id);if(!p)return;const current=cart.find(i=>i.id===id);if((current?.qty||0)>=p.stock)return notify(t('You have reached the available quantity.'));setLastOrder(null);setCart(previous=>{const item=previous.find(i=>i.id===id);if((item?.qty||0)>=p.stock)return previous;return item?previous.map(i=>i.id===id?{...i,qty:i.qty+1}:i):[...previous,{id,qty:1}];});notify(t('{name} added to your cart',{name:p.name}));}
 function changeQuantity(id,delta){const p=findProduct(id),i=cart.find(i=>i.id===id);if(!p||!i)return;if(i.qty+delta>p.stock)return notify(t('No more stock available.'));setCart(previous=>previous.map(i=>i.id===id?{...i,qty:i.qty+delta}:i).filter(i=>i.qty>0));}
 function confirmLocation(lat,lng){if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)throw new Error(t('Enter valid latitude and longitude.'));if(!catalog)throw new Error(t('Please wait for the shop to load.'));const s=catalog.settings,km=s.hubLat===null||s.hubLng===null?null:distance(s.hubLat,s.hubLng,lat,lng);setLocation({lat,lng,km,eligible:km!==null&&km<=s.radius});setLocationError('');}
 function locate(){if(!catalog)return notify(t('The catalogue is loading. Please retry shortly.'));if(locationLock.current)return;if(!navigator.geolocation){setLocationError(t('Location unavailable. Enter a delivery pin at checkout.'));return;}locationLock.current=true;setLocating(true);setLocationError('');const done=()=>{locationLock.current=false;setLocating(false);};navigator.geolocation.getCurrentPosition(p=>{done();confirmLocation(p.coords.latitude,p.coords.longitude);},e=>{done();setLocation(null);setLocationError(e.code===1?t('Location permission denied. Allow access in browser settings, or enter your delivery pin at checkout.'):t('Location unavailable. Turn on device location, or enter your delivery pin at checkout.'));},{enableHighAccuracy:true,timeout:12000,maximumAge:60000});}
 const radius=catalog?.settings.radius??15;
 const locationMessage=locating?t('Finding your location…'):locationError||(!location?t('Turn on location to check delivery within {radius} km of our hub.',{radius}):location.km===null?t('Delivery hub is not configured yet. Shop pickup is available.'):location.eligible?t('Delivery available · {distance} km from our hub',{distance:location.km.toFixed(1)}):t('Outside our {radius} km delivery area · Shop pickup available',{radius}));
 const totals=useMemo(()=>({count:cart.reduce((s,i)=>s+i.qty,0),subtotal:cart.reduce((s,i)=>s+(findProduct(i.id)?sellingPrice(findProduct(i.id))*i.qty:0),0),savings:cart.reduce((s,i)=>{const p=findProduct(i.id);if(!p)return s;const original=p.items?p.items.reduce((sum,x)=>sum+(findProduct(x.id)?.price||0)*x.qty,0):p.price;return s+Math.max(0,original-sellingPrice(p))*i.qty;},0)}),[cart,findProduct]);
 const openCart=()=>{if(!catalog)return notify(t('The shop is still loading. Please retry shortly.'));setCartOpen(true);};
 return <ShopContext.Provider value={{catalog,loading,error,loadCatalog,cart,setCart,totals,findProduct,addToCart,changeQuantity,toast,notify,location,locationMessage,locating,locate,confirmLocation,cartOpen,setCartOpen,openCart,lastOrder,setLastOrder,online}}>{children}</ShopContext.Provider>;
}
